function PMA_urldecode(c){return decodeURIComponent(c.replace(/\+/g,"%20"))}function getFieldName(c,b){if(b=="vertical"){var a=c.siblings("th").find("a").text();if(""==a)a=c.siblings("th").text()}else{var d=c.index();a=$("#table_results").find("thead").find("th:nth("+(d-4)+") a").text();if(""==a)a=$("#table_results").find("thead").find("th:nth("+(d-4)+")").text()}return a=$.trim(a)}
function appendInlineAnchor(){if($("#top_direction_dropdown").val()=="vertical"){$("#table_results tr").find(".edit_row_anchor").removeClass(".edit_row_anchor").parent().each(function(){var c=$(this),b=c.clone(),a=b.find("img:first").attr("title",PMA_messages.strInlineEdit),d=a.attr("src").replace(/b_edit/,"b_inline_edit");a.attr("src",d);b.find("td").addClass("inline_edit_anchor").find("a").attr("href","#").find("span").text(" "+PMA_messages.strInlineEdit).prepend(a);b.insertAfter(c)});$("#table_results").find("tr").find(":checkbox").closest("tr").find("th").attr("rowspan",
"4")}else{$(".edit_row_anchor").each(function(){$this_td=$(this);$this_td.removeClass("edit_row_anchor");var c=$this_td.clone(),b=c.find("img").attr("title",PMA_messages.strInlineEdit),a=b.attr("src").replace(/b_edit/,"b_inline_edit");b.attr("src",a);c.addClass("inline_edit_anchor").find("a").attr("href","#").find("span").text(" "+PMA_messages.strInlineEdit).prepend(b);$this_td.after(c)});$("#rowsDeleteForm").find("thead, tbody").find("th").each(function(){var c=$(this);c.attr("colspan")==4&&c.attr("colspan",
"5")})}}
$(document).ready(function(){$.ajaxSetup({cache:"false"});var c=$("#top_direction_dropdown").val();$("#top_direction_dropdown, #bottom_direction_dropdown").live("change",function(){c=$(this).val()});$("#sqlqueryresults").live("appendAnchor",function(){appendInlineAnchor()});$("#sqlqueryresults.ajax").trigger("appendAnchor");if(!$("#sqlqueryform").find("a").is("#togglequerybox")){$('<a id="togglequerybox"></a>').html(PMA_messages.strHideQueryBox).appendTo("#sqlqueryform");$("#togglequerybox").bind("click",function(){var b=
$(this);b.siblings().slideToggle("medium");b.text()==PMA_messages.strHideQueryBox?b.text(PMA_messages.strShowQueryBox):b.text(PMA_messages.strHideQueryBox);return false})}$("#sqlqueryform.ajax").live("submit",function(b){b.preventDefault();$(".error").remove();$form=$(this);PMA_ajaxShowMessage();$form.find("input:hidden").is("#ajax_request_hidden")||$form.append('<input type="hidden" id="ajax_request_hidden" name="ajax_request" value="true" />');$.post($(this).attr("action"),$(this).serialize(),function(a){if(a.success==
true){$(".success").fadeOut();$("#sqlqueryform").before(a.message);$("#sqlqueryresults").show();if(typeof a.reload!="undefined"){$form.find("input[name=db]").val(a.db);$form.find("input[name=ajax_request]").remove();$form.append('<input type="hidden" name="reload" value="true" />');$.post("db_sql.php",$form.serialize(),function(d){$("body").html(d)})}}else if(a.success==false){$("#sqlqueryform").before(a.error);$("#sqlqueryresults").hide()}else{$("#sqlqueryresults").show();$("#sqlqueryresults").html(a);
$("#sqlqueryresults").trigger("appendAnchor");$("#togglequerybox").siblings(":visible").length>0&&$("#togglequerybox").trigger("click");PMA_init_slider()}})});$("input[name=navig].ajax").live("click",function(b){b.preventDefault();PMA_ajaxShowMessage();b=$(this).parent("form");b.append('<input type="hidden" name="ajax_request" value="true" />');$.post(b.attr("action"),b.serialize(),function(a){$("#sqlqueryresults").html(a);$("#sqlqueryresults").trigger("appendAnchor");PMA_init_slider()})});$("#pageselector").live("change",
function(b){var a=$(this).parent("form");if($(this).hasClass("ajax")){b.preventDefault();PMA_ajaxShowMessage();$.post(a.attr("action"),a.serialize()+"&ajax_request=true",function(d){$("#sqlqueryresults").html(d);$("#sqlqueryresults").trigger("appendAnchor");PMA_init_slider()})}else a.submit()});$("#table_results.ajax").find("a[title=Sort]").live("click",function(b){b.preventDefault();PMA_ajaxShowMessage();$anchor=$(this);$.get($anchor.attr("href"),$anchor.serialize()+"&ajax_request=true",function(a){$("#sqlqueryresults").html(a).trigger("appendAnchor")})});
$("#displayOptionsForm.ajax").live("submit",function(b){b.preventDefault();$form=$(this);$.post($form.attr("action"),$form.serialize()+"&ajax_request=true",function(a){$("#sqlqueryresults").html(a).trigger("appendAnchor");PMA_init_slider()})});$(".inline_edit_anchor").live("click",function(b){b.preventDefault();$(this).removeClass("inline_edit_anchor").addClass("inline_edit_active");if(c=="vertical"){b=$(this).index();var a=$(this).parents("tbody").find("tr").find(".inline_edit:nth("+b+")"),d=$(this).parents("tbody").find("tr").find(".where_clause:nth("+
b+")").val()}else{a=$(this).parent("tr").find(".inline_edit");d=$(this).parent("tr").find(".where_clause").val()}a.each(function(){var k=$(this).html(),f=$(this),h=getFieldName(f,c);if(f.is(":not(.truncated, .transformed, .relation, .enum, .null)")){f.html("<textarea>"+k+"</textarea>").append('<span class="original_data">'+k+"</span>");$(".original_data").hide()}else if(f.is(".truncated, .transformed"))$.post("sql.php",{token:window.parent.token,db:window.parent.db,ajax_request:true,sql_query:"SELECT "+
h+" FROM "+window.parent.table+" WHERE "+d,inline_edit:true},function(i){if(i.success==true){f.html("<textarea>"+i.value+"</textarea>").append('<span class="original_data">'+k+"</span>");$(".original_data").hide()}else PMA_ajaxShowMessage(i.error)});else if(f.is(".relation")){var l=f.find("a").text();h={ajax_request:true,get_relational_values:true,db:window.parent.db,table:window.parent.table,column:h,token:window.parent.token,curr_value:l};$.post("sql.php",h,function(i){f.html(i.dropdown).append('<span class="original_data">'+
k+"</span>");$(".original_data").hide()})}else if(f.is(".enum")){l=f.text();h={ajax_request:true,get_enum_values:true,db:window.parent.db,table:window.parent.table,column:h,token:window.parent.token,curr_value:l};$.post("sql.php",h,function(i){f.html(i.dropdown).append('<span class="original_data">'+k+"</span>");$(".original_data").hide()})}else if(f.is(".null")){f.html("<textarea></textarea>").append('<span class="original_data">NULL</span>');$(".original_data").hide()}})});$(".inline_edit_active").live("click",
function(b){b.preventDefault();var a=$(this),d="";if(c=="vertical"){b=a.index();var k=a.parents("tbody").find("tr").find(".inline_edit:nth("+b+")");b=a.parents("tbody").find("tr").find(".where_clause:nth("+b+")").val()}else{k=a.parent("tr").find(".inline_edit");b=a.parent("tr").find(".where_clause").val()}var f=a.is(".nonunique")?0:1,h={},l={},i={},q=false;k.each(function(){var e=$(this),g=getFieldName(e,c),j={};if(e.is(".transformed"))q=true;if(e.is(":not(.relation, .enum)")){j[g]=e.find("textarea").val();
e.is(".transformed")&&$.extend(i,j)}else{d=e.find("select");if(d.length!=0)j[g]=d.val();d=e.find("span.curr_value");if(d.length!=0)j[g]=d.text();e.is(".relation")&&$.extend(l,j)}$.extend(h,j)});var m="UPDATE "+window.parent.table+" SET ";$.each(h,function(e,g){if(g.length==0)g="NULL";m+=" "+e+"='"+g.replace(/'/g,"''")+"' , "});m=m.replace(/,\s$/,"");m+=" WHERE "+PMA_urldecode(b);var r=$.param(l),s=$.param(i);$.post("tbl_replace.php",{ajax_request:true,sql_query:m,disp_direction:c,token:window.parent.token,
db:window.parent.db,table:window.parent.table,clause_is_unique:f,where_clause:b,rel_fields_list:r,do_transformations:q,transform_fields_list:s,"goto":"sql.php",submit_type:"save"},function(e){if(e.success==true){PMA_ajaxShowMessage(e.message);a.removeClass("inline_edit_active").addClass("inline_edit_anchor");k.each(function(){$this_sibling=$(this);if($this_sibling.is(":not(.relation, .enum)")){var g=$this_sibling.find("textarea").val();if($this_sibling.is(".transformed")){var j=getFieldName($this_sibling,
c);$.each(e.transformations,function(p,n){if(p==j){if($this_sibling.is(".text_plain, .application_octetstream"))g=n;else{var t=$this_sibling.find("textarea").val();g=$(n).append(t)}return false}})}}else{var o=g="";d=$this_sibling.find("select");if(d.length!=0)o=d.val();d=$this_sibling.find("span.curr_value");if(d.length!=0)o=d.text();if($this_sibling.is(".relation")){j=getFieldName($this_sibling,c);$.each(e.relations,function(p,n){if(p==j){g=$(n).append(o);return false}})}if($this_sibling.is(".enum"))g=
o}$this_sibling.html(g)})}else PMA_ajaxShowMessage(e.error)})})},"top.frame_content");function PMA_changeClassForColumn(c,b){var a=c.index();a--;c.closest("table").find("tbody tr ").has("td.data").each(function(){$(this).find("td.data:eq("+a+")").toggleClass(b)})}
$(document).ready(function(){$(".browse_foreign").live("click",function(c){c.preventDefault();window.open(this.href,"foreigners","width=640,height=240,scrollbars=yes,resizable=yes");$anchor=$(this);$anchor.addClass("browse_foreign_clicked");return false});$(".column_heading").live("hover",function(){PMA_changeClassForColumn($(this),"hover")});$(".column_heading").live("click",function(){PMA_changeClassForColumn($(this),"marked")})});
